// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Register.proto

package com.meteor.minaserver;

public final class RegisterProtoBuf {
  private RegisterProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RegisterMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RegisterMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .MessageBase msgbase = 1;</code>
     *
     * <pre>
     *所有类型都必须包含此类型，并且必须是第一个
     * </pre>
     */
    boolean hasMsgbase();
    /**
     * <code>required .MessageBase msgbase = 1;</code>
     *
     * <pre>
     *所有类型都必须包含此类型，并且必须是第一个
     * </pre>
     */
    com.meteor.minaserver.MessageBaseProtoBuf.MessageBase getMsgbase();
    /**
     * <code>required .MessageBase msgbase = 1;</code>
     *
     * <pre>
     *所有类型都必须包含此类型，并且必须是第一个
     * </pre>
     */
    com.meteor.minaserver.MessageBaseProtoBuf.MessageBaseOrBuilder getMsgbaseOrBuilder();

    /**
     * <code>required string account = 2;</code>
     */
    boolean hasAccount();
    /**
     * <code>required string account = 2;</code>
     */
    java.lang.String getAccount();
    /**
     * <code>required string account = 2;</code>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <code>required string password = 3;</code>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 3;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>required string password = 3;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>optional string name = 4;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 4;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 4;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 sex = 5;</code>
     */
    boolean hasSex();
    /**
     * <code>optional int32 sex = 5;</code>
     */
    int getSex();

    /**
     * <code>optional int32 telephone = 6;</code>
     */
    boolean hasTelephone();
    /**
     * <code>optional int32 telephone = 6;</code>
     */
    int getTelephone();
  }
  /**
   * Protobuf type {@code RegisterMsg}
   */
  public static final class RegisterMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RegisterMsg)
      RegisterMsgOrBuilder {
    // Use RegisterMsg.newBuilder() to construct.
    private RegisterMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RegisterMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RegisterMsg defaultInstance;
    public static RegisterMsg getDefaultInstance() {
      return defaultInstance;
    }

    public RegisterMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RegisterMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.meteor.minaserver.MessageBaseProtoBuf.MessageBase.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = msgbase_.toBuilder();
              }
              msgbase_ = input.readMessage(com.meteor.minaserver.MessageBaseProtoBuf.MessageBase.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msgbase_);
                msgbase_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              account_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              password_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              name_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              sex_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              telephone_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.meteor.minaserver.RegisterProtoBuf.internal_static_RegisterMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.meteor.minaserver.RegisterProtoBuf.internal_static_RegisterMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.meteor.minaserver.RegisterProtoBuf.RegisterMsg.class, com.meteor.minaserver.RegisterProtoBuf.RegisterMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<RegisterMsg> PARSER =
        new com.google.protobuf.AbstractParser<RegisterMsg>() {
      public RegisterMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegisterMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RegisterMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MSGBASE_FIELD_NUMBER = 1;
    private com.meteor.minaserver.MessageBaseProtoBuf.MessageBase msgbase_;
    /**
     * <code>required .MessageBase msgbase = 1;</code>
     *
     * <pre>
     *所有类型都必须包含此类型，并且必须是第一个
     * </pre>
     */
    public boolean hasMsgbase() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .MessageBase msgbase = 1;</code>
     *
     * <pre>
     *所有类型都必须包含此类型，并且必须是第一个
     * </pre>
     */
    public com.meteor.minaserver.MessageBaseProtoBuf.MessageBase getMsgbase() {
      return msgbase_;
    }
    /**
     * <code>required .MessageBase msgbase = 1;</code>
     *
     * <pre>
     *所有类型都必须包含此类型，并且必须是第一个
     * </pre>
     */
    public com.meteor.minaserver.MessageBaseProtoBuf.MessageBaseOrBuilder getMsgbaseOrBuilder() {
      return msgbase_;
    }

    public static final int ACCOUNT_FIELD_NUMBER = 2;
    private java.lang.Object account_;
    /**
     * <code>required string account = 2;</code>
     */
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string account = 2;</code>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          account_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string account = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 3;
    private java.lang.Object password_;
    /**
     * <code>required string password = 3;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string password = 3;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 4;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 4;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string name = 4;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 5;
    private int sex_;
    /**
     * <code>optional int32 sex = 5;</code>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 sex = 5;</code>
     */
    public int getSex() {
      return sex_;
    }

    public static final int TELEPHONE_FIELD_NUMBER = 6;
    private int telephone_;
    /**
     * <code>optional int32 telephone = 6;</code>
     */
    public boolean hasTelephone() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 telephone = 6;</code>
     */
    public int getTelephone() {
      return telephone_;
    }

    private void initFields() {
      msgbase_ = com.meteor.minaserver.MessageBaseProtoBuf.MessageBase.getDefaultInstance();
      account_ = "";
      password_ = "";
      name_ = "";
      sex_ = 0;
      telephone_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsgbase()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMsgbase().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, msgbase_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAccountBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, sex_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, telephone_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, msgbase_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAccountBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, sex_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, telephone_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.meteor.minaserver.RegisterProtoBuf.RegisterMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.meteor.minaserver.RegisterProtoBuf.RegisterMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.meteor.minaserver.RegisterProtoBuf.RegisterMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.meteor.minaserver.RegisterProtoBuf.RegisterMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.meteor.minaserver.RegisterProtoBuf.RegisterMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.meteor.minaserver.RegisterProtoBuf.RegisterMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.meteor.minaserver.RegisterProtoBuf.RegisterMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.meteor.minaserver.RegisterProtoBuf.RegisterMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.meteor.minaserver.RegisterProtoBuf.RegisterMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.meteor.minaserver.RegisterProtoBuf.RegisterMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.meteor.minaserver.RegisterProtoBuf.RegisterMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RegisterMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RegisterMsg)
        com.meteor.minaserver.RegisterProtoBuf.RegisterMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.meteor.minaserver.RegisterProtoBuf.internal_static_RegisterMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.meteor.minaserver.RegisterProtoBuf.internal_static_RegisterMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.meteor.minaserver.RegisterProtoBuf.RegisterMsg.class, com.meteor.minaserver.RegisterProtoBuf.RegisterMsg.Builder.class);
      }

      // Construct using com.meteor.minaserver.RegisterProtoBuf.RegisterMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMsgbaseFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (msgbaseBuilder_ == null) {
          msgbase_ = com.meteor.minaserver.MessageBaseProtoBuf.MessageBase.getDefaultInstance();
        } else {
          msgbaseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        account_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        sex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        telephone_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.meteor.minaserver.RegisterProtoBuf.internal_static_RegisterMsg_descriptor;
      }

      public com.meteor.minaserver.RegisterProtoBuf.RegisterMsg getDefaultInstanceForType() {
        return com.meteor.minaserver.RegisterProtoBuf.RegisterMsg.getDefaultInstance();
      }

      public com.meteor.minaserver.RegisterProtoBuf.RegisterMsg build() {
        com.meteor.minaserver.RegisterProtoBuf.RegisterMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.meteor.minaserver.RegisterProtoBuf.RegisterMsg buildPartial() {
        com.meteor.minaserver.RegisterProtoBuf.RegisterMsg result = new com.meteor.minaserver.RegisterProtoBuf.RegisterMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (msgbaseBuilder_ == null) {
          result.msgbase_ = msgbase_;
        } else {
          result.msgbase_ = msgbaseBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.telephone_ = telephone_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.meteor.minaserver.RegisterProtoBuf.RegisterMsg) {
          return mergeFrom((com.meteor.minaserver.RegisterProtoBuf.RegisterMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.meteor.minaserver.RegisterProtoBuf.RegisterMsg other) {
        if (other == com.meteor.minaserver.RegisterProtoBuf.RegisterMsg.getDefaultInstance()) return this;
        if (other.hasMsgbase()) {
          mergeMsgbase(other.getMsgbase());
        }
        if (other.hasAccount()) {
          bitField0_ |= 0x00000002;
          account_ = other.account_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000004;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000008;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        if (other.hasTelephone()) {
          setTelephone(other.getTelephone());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgbase()) {
          
          return false;
        }
        if (!hasAccount()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        if (!getMsgbase().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.meteor.minaserver.RegisterProtoBuf.RegisterMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.meteor.minaserver.RegisterProtoBuf.RegisterMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.meteor.minaserver.MessageBaseProtoBuf.MessageBase msgbase_ = com.meteor.minaserver.MessageBaseProtoBuf.MessageBase.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.meteor.minaserver.MessageBaseProtoBuf.MessageBase, com.meteor.minaserver.MessageBaseProtoBuf.MessageBase.Builder, com.meteor.minaserver.MessageBaseProtoBuf.MessageBaseOrBuilder> msgbaseBuilder_;
      /**
       * <code>required .MessageBase msgbase = 1;</code>
       *
       * <pre>
       *所有类型都必须包含此类型，并且必须是第一个
       * </pre>
       */
      public boolean hasMsgbase() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .MessageBase msgbase = 1;</code>
       *
       * <pre>
       *所有类型都必须包含此类型，并且必须是第一个
       * </pre>
       */
      public com.meteor.minaserver.MessageBaseProtoBuf.MessageBase getMsgbase() {
        if (msgbaseBuilder_ == null) {
          return msgbase_;
        } else {
          return msgbaseBuilder_.getMessage();
        }
      }
      /**
       * <code>required .MessageBase msgbase = 1;</code>
       *
       * <pre>
       *所有类型都必须包含此类型，并且必须是第一个
       * </pre>
       */
      public Builder setMsgbase(com.meteor.minaserver.MessageBaseProtoBuf.MessageBase value) {
        if (msgbaseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msgbase_ = value;
          onChanged();
        } else {
          msgbaseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .MessageBase msgbase = 1;</code>
       *
       * <pre>
       *所有类型都必须包含此类型，并且必须是第一个
       * </pre>
       */
      public Builder setMsgbase(
          com.meteor.minaserver.MessageBaseProtoBuf.MessageBase.Builder builderForValue) {
        if (msgbaseBuilder_ == null) {
          msgbase_ = builderForValue.build();
          onChanged();
        } else {
          msgbaseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .MessageBase msgbase = 1;</code>
       *
       * <pre>
       *所有类型都必须包含此类型，并且必须是第一个
       * </pre>
       */
      public Builder mergeMsgbase(com.meteor.minaserver.MessageBaseProtoBuf.MessageBase value) {
        if (msgbaseBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              msgbase_ != com.meteor.minaserver.MessageBaseProtoBuf.MessageBase.getDefaultInstance()) {
            msgbase_ =
              com.meteor.minaserver.MessageBaseProtoBuf.MessageBase.newBuilder(msgbase_).mergeFrom(value).buildPartial();
          } else {
            msgbase_ = value;
          }
          onChanged();
        } else {
          msgbaseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .MessageBase msgbase = 1;</code>
       *
       * <pre>
       *所有类型都必须包含此类型，并且必须是第一个
       * </pre>
       */
      public Builder clearMsgbase() {
        if (msgbaseBuilder_ == null) {
          msgbase_ = com.meteor.minaserver.MessageBaseProtoBuf.MessageBase.getDefaultInstance();
          onChanged();
        } else {
          msgbaseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .MessageBase msgbase = 1;</code>
       *
       * <pre>
       *所有类型都必须包含此类型，并且必须是第一个
       * </pre>
       */
      public com.meteor.minaserver.MessageBaseProtoBuf.MessageBase.Builder getMsgbaseBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMsgbaseFieldBuilder().getBuilder();
      }
      /**
       * <code>required .MessageBase msgbase = 1;</code>
       *
       * <pre>
       *所有类型都必须包含此类型，并且必须是第一个
       * </pre>
       */
      public com.meteor.minaserver.MessageBaseProtoBuf.MessageBaseOrBuilder getMsgbaseOrBuilder() {
        if (msgbaseBuilder_ != null) {
          return msgbaseBuilder_.getMessageOrBuilder();
        } else {
          return msgbase_;
        }
      }
      /**
       * <code>required .MessageBase msgbase = 1;</code>
       *
       * <pre>
       *所有类型都必须包含此类型，并且必须是第一个
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.meteor.minaserver.MessageBaseProtoBuf.MessageBase, com.meteor.minaserver.MessageBaseProtoBuf.MessageBase.Builder, com.meteor.minaserver.MessageBaseProtoBuf.MessageBaseOrBuilder> 
          getMsgbaseFieldBuilder() {
        if (msgbaseBuilder_ == null) {
          msgbaseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.meteor.minaserver.MessageBaseProtoBuf.MessageBase, com.meteor.minaserver.MessageBaseProtoBuf.MessageBase.Builder, com.meteor.minaserver.MessageBaseProtoBuf.MessageBaseOrBuilder>(
                  getMsgbase(),
                  getParentForChildren(),
                  isClean());
          msgbase_ = null;
        }
        return msgbaseBuilder_;
      }

      private java.lang.Object account_ = "";
      /**
       * <code>required string account = 2;</code>
       */
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string account = 2;</code>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            account_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string account = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string account = 2;</code>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string account = 2;</code>
       */
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>required string account = 2;</code>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        account_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>required string password = 3;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string password = 3;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string password = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 3;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 3;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000004);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 3;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 4;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }

      private int sex_ ;
      /**
       * <code>optional int32 sex = 5;</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 sex = 5;</code>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <code>optional int32 sex = 5;</code>
       */
      public Builder setSex(int value) {
        bitField0_ |= 0x00000010;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sex = 5;</code>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sex_ = 0;
        onChanged();
        return this;
      }

      private int telephone_ ;
      /**
       * <code>optional int32 telephone = 6;</code>
       */
      public boolean hasTelephone() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 telephone = 6;</code>
       */
      public int getTelephone() {
        return telephone_;
      }
      /**
       * <code>optional int32 telephone = 6;</code>
       */
      public Builder setTelephone(int value) {
        bitField0_ |= 0x00000020;
        telephone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 telephone = 6;</code>
       */
      public Builder clearTelephone() {
        bitField0_ = (bitField0_ & ~0x00000020);
        telephone_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RegisterMsg)
    }

    static {
      defaultInstance = new RegisterMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RegisterMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegisterMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RegisterMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Register.proto\032\021MessageBase.proto\"}\n\013R" +
      "egisterMsg\022\035\n\007msgbase\030\001 \002(\0132\014.MessageBas" +
      "e\022\017\n\007account\030\002 \002(\t\022\020\n\010password\030\003 \002(\t\022\014\n\004" +
      "name\030\004 \001(\t\022\013\n\003sex\030\005 \001(\005\022\021\n\ttelephone\030\006 \001" +
      "(\005B)\n\025com.meteor.minaserverB\020RegisterPro" +
      "toBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.meteor.minaserver.MessageBaseProtoBuf.getDescriptor(),
        }, assigner);
    internal_static_RegisterMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RegisterMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RegisterMsg_descriptor,
        new java.lang.String[] { "Msgbase", "Account", "Password", "Name", "Sex", "Telephone", });
    com.meteor.minaserver.MessageBaseProtoBuf.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
